name: arvet-2.0
channels:
  - defaults
  - conda-forge
dependencies:
  - h5py
  - numpy
  - matplotlib
  - pillow
  - pip
  - py-opencv
  - pymongo
  - python>=3.7
  - pyyaml
  - setuptools
  - wheel
  - pip:
    - mongomock
    - pymodm
    - transforms3d
    - xxhash

