import sys
import bson.objectid
import config.global_configuration as global_conf
import database.client
import batch_analysis.trial_runner as trial_runner


def main():
    """
    Train a given system system with a given data source as a training set
    This represents a basic task.
    Scripts to run this will be autogenerated by the job system
    :return: 
    """
    if len(sys.argv) >= 3:
        # TODO: Get system trainers from the database, train with dataset and add to systems collection
        system_id = bson.objectid.ObjectId(sys.argv[1])
        image_source_id = bson.objectid.ObjectId(sys.argv[2])

        config = global_conf.load_global_config('config.yml')
        db_client = database.client.DatabaseClient(config=config)

        s_system = db_client.system_collection.find_one({'_id': system_id})
        system = db_client.deserialize_entity(s_system)

        s_image_source = db_client.image_source_collection.find_one({'_id': image_source_id})
        image_source = db_client.deserialize_entity(s_image_source)
        if hasattr('load', image_source):
            image_source.load(db_client)

        trial_result = trial_runner.run_system_with_source(system, image_source)
        db_client.trials_collection.insert(trial_result.serialize())


if __name__ == '__main__':
    main()
